# https://docs.travis-ci.com/user/languages/php/
language: php
sudo: false
php:
  - 7.1
  - 7.0
  - hhvm
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
before_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:4} = hhvm ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi
script:
  - php test.php
